### ISSUE TITLE
Failure: Module initialization failed

### ISSUE THREAD

**Issue by l3lackShark** [hikkamorii/hikkaAVStream#1]
insmod: ERROR: could not insert module v4l2loopback.ko: Invalid module format
29
30
31
32

![image](https://user-images.githubusercontent.com/20248967/73352497-0e9d7200-42b3-11ea-9930-47701f274839.png)

Great fork! Can't get this to work unfortunately..

P.S. Mon2Cam works fine.

**Comment by hikkamorii** [comment]
Hi! Glad you liked it!

Pay attention to the comments towards the end of a script:

```
# Uncomment this if you want to use kernel module from package manager:

#sudo modprobe v4l2loopback devices=1 video_nr=$DEVICE exclusive_caps=1




# Uncomment this if you're running Ubuntu on kernel 5.0.0-25:

sudo insmod $VL2LKO devices=1 video_nr=$DEVICE exclusive_caps=1

# Make sure to compile module for your kernel if you have to.
```

So just uncomment first command and comment second.

Hopefully I'll improve user-friendliness of this script later 😅
